### ISSUE TITLE
Revypython meta-issue

### ISSUE THREAD

**Issue by Mortal** [TK-IT/revypython#5]
Rolleliste
- [ ] Parse manus til rolleliste (sendes til revyister)
- [ ] Parse rolleprioriteringer til overblik over prioriteringer
- [ ] Parse manus til rollefordelings-regneark (csv: nummer, rollenavn, (rolletype), (revyist))

Rollefordeling
Sang vs. sketch
Stor vs. lille
m/k/n
- [ ] Output-ark (csv: nummer, rollenavn, rolletype, revyist)
- [ ] Oversigt: antal roller pr. rolletype pr. revyist + ej fordelte

Farvekodning
